BluetoothAudio: change singleton implementation to Create/Destroy bas…
rdkcentral/ThunderClientLibraries pull request #278
Opened 2024-07-24 12:11 UTC by HaseenaSainul

…ed on requirement

2024-07-24 12:26 UTC, sebaszm requested changes
This is still holding a central instance and will fail for init, init, deinit, deinit scenario (ie. multiple clients). It either needs to be reference counted or keeping of the instance needs to be offloaded to the client (ie the API passing a handle).

2024-07-24 14:44 UTC, HaseenaSainul commented
> This is still holding a central instance and will fail for init, init, deinit, deinit scenario (ie. multiple clients). It either needs to be reference counted or keeping of the instance needs to be offloaded to the client (ie the API passing a handle).

updated the code

2024-07-26 10:45 UTC, sebaszm commented on Source/bluetoothaudiosink/BluetoothAudioSink.cpp
> +            if (_instance == nullptr) {
Doesnt this need a lock?

2024-07-26 11:41 UTC, HaseenaSainul commented on Source/bluetoothaudiosink/BluetoothAudioSink.cpp
> +            if (_instance == nullptr) {
yes, added. Thanks for the comments :)

2024-07-30 07:19 UTC, sebaszm submitted a review, later dismissed

2024-08-05 11:01 UTC, pwielders approved these changes

2024-08-05 11:01 UTC, merged