DELIA-49951 DELIA-49978: add locking
rdkcentral/ThunderClientLibraries pull request #77
Opened 2021-06-15 17:57 UTC by npoltorapavlo

Reason for change: temporary solution for multiprocess
access to Core::IPCChannelClientType.
Test Procedure: Multiple processes should get token
in parallel.
Risks: Low
Signed-off-by: Nikita Poltorapavlo <npoltorapavlo@productengine.com>

2021-06-29 11:50 UTC, pwielders commented
I would not call this a low risk change :-) What happens if the process that owns the lock, crashes. It will deadlock all other process that require a token. Hence why we ported back the change we made on R3 to allow for a 1-N cardinality in stead of the 1-1 cardinality that existed. This way different process also can concurrently ask for a token. Ni implicit serialization. I assume with this functionality change, this PR can be closed ?

2021-06-29 11:53 UTC, pwielders requested changes
Think this PR is outdated as we currently allow multiple connections to the SecurityAgent plugin and the solution is quite risky.

2021-06-29 17:22 UTC, npoltorapavlo commented
@pwielders, the solution from R3 crashes in R2 (changeset included ThunderClientLibraries/pull/78, rdkservices/pull/1400). This PR is the solution at the moment. Lock is released on crash, as tested.

2021-07-05 08:56 UTC, pwielders commented
Oke  trying to find the Crashlog for R2. Can not find it. Could you send a reference to crashlog so we can investigate.
 
Indeed did a bit of googling and for Linux it seems safe: https://stackoverflow.com/questions/12651068/release-of-flock -in-case-of-errors however the file lock will stil cause serialization of getting the token hence why the solution created in R3, and pirted to R2, multiple requests can be handled at the same time, is still the preferred solution, so will not merge this but lets fix the issue you observe using this solution.

2021-07-06 11:36 UTC, npoltorapavlo commented
Crash is in WPEFramework::RPC::Administrator::DeleteChannel, line: loop->Unknown()->Release(). `(gdb) p loop
$1 = {
  _interfaceId = 41,
  _interface = 0x0,
  _referenceCount = 1
}`
https://ccp.sys.comcast.net/browse/DELIA-51244

2021-08-05 11:39 UTC, MFransen69 commented
I think the crash is resolved now. Also saw that the proper solution is merged. Hope we can close this PR now?

2021-08-05 11:48 UTC, closed without merging